// Definition of all action type constants and their types

export const REQUEST_DISCOVER_TV_SHOWS = 'REQUEST_DISCOVER_TV_SHOWS';
export type REQUEST_DISCOVER_TV_SHOWS = typeof REQUEST_DISCOVER_TV_SHOWS;
export const RECEIVE_DISCOVER_TV_SHOWS = 'RECEIVE_DISCOVER_TV_SHOWS';
export type RECEIVE_DISCOVER_TV_SHOWS = typeof RECEIVE_DISCOVER_TV_SHOWS;

export const REQUEST_TV_SHOW = 'REQUEST_TV_SHOW';
export type REQUEST_TV_SHOW = typeof REQUEST_TV_SHOW;
export const RECEIVE_TV_SHOW = 'RECEIVE_TV_SHOW';
export type RECEIVE_TV_SHOW = typeof RECEIVE_TV_SHOW;

export const REQUEST_TV_SEASONS = 'REQUEST_TV_SEASONS';
export type REQUEST_TV_SEASONS = typeof REQUEST_TV_SEASONS;
export const RECEIVE_TV_SEASONS = 'RECEIVE_TV_SEASONS';
export type RECEIVE_TV_SEASONS = typeof RECEIVE_TV_SEASONS;

export const REQUEST_TV_EPISODE = 'REQUEST_TV_EPISODE';
export type REQUEST_TV_EPISODE = typeof REQUEST_TV_EPISODE;
export const RECEIVE_TV_EPISODE = 'RECEIVE_TV_EPISODE';
export type RECEIVE_TV_EPISODE = typeof RECEIVE_TV_EPISODE;


export const API_CALL_ERROR = 'API_CALL_ERROR';
export type API_CALL_ERROR = typeof API_CALL_ERROR;
